// Generated by CoffeeScript 1.3.3
(function() {
  var get_case,
    _this = this;

  get_case = function() {
    var case_n,
      _this = this;
    case_n = $("#case").val();
    console.log(case_n);
    return $.get("/images/" + case_n, function(data_images) {
      console.log("getting " + case_n);
      console.log(data_images);
      window.data_images = data_images;
      return render_template("images", data_images);
    });
  };

  window.get_case = get_case;

  $(document).ready(function() {
    console.log("here I am, suffering");
    return $("#find").click(function() {
      return get_case();
    });
  });

}).call(this);
