// Generated by CoffeeScript 1.3.3
(function() {
  var get_case, get_images, get_results,
    _this = this;

  get_case = function() {
    var case_n;
    case_n = $("#case").val();
    console.log;
    if (case_n) {
      get_images(case_n);
      return get_results(case_n);
    }
  };

  get_images = function(case_n) {
    var _this = this;
    return $.get("/images/" + case_n, function(data_images) {
      console.log("getting images=" + case_n);
      console.log(data_images);
      window.data_images = data_images;
      return render_template("images", data_images);
    });
  };

  window.get_images = get_images;

  get_results = function(case_n) {
    var _this = this;
    return $.get("/results/" + case_n, function(data_results) {
      console.log("getting results=" + case_n);
      console.log(data_results);
      window.data_results = data_results;
      return render_template("results", data_results);
    });
  };

  window.get_results = get_results;

  $(document).ready(function() {
    console.log("here I am, suffering");
    $("#find").click(function() {
      return get_case();
    });
    return get_case();
  });

}).call(this);
